<?php

namespace Jabe\Engine\Runtime;

interface ProcessInstanceModificationInstantiationBuilderInterface extends ProcessInstanceModificationBuilderInterface, ActivityInstantiationBuilderInterface
{
}
