<?php

namespace BpmPlatform\Engine\Runtime;

interface ProcessInstanceModificationInstantiationBuilderInterface extends ProcessInstanceModificationBuilderInterface, ActivityInstantiationBuilderInterface
{
}
